import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

function read(path) {
  return readFileSync(new URL(`../${path}`, import.meta.url), 'utf8')
}

const app = read('src/App.jsx')
const main = read('src/main.jsx')
const index = read('index.html')
const manifest = read('public/manifest.webmanifest')
const serviceWorker = read('public/sw.js')
const pwaUpdate = read('src/services/app/pwaUpdate.js')
const liveScreen = read('src/components/live/LiveScreen.jsx')
const liveHeader = read('src/components/live/LiveHeader.jsx')
const liveActions = read('src/components/live/LiveActions.jsx')
const liveChat = read('src/components/live/LiveChat.jsx')
const preLive = read('src/components/live/PreLiveSetupPanel.jsx')
const discover = read('src/components/discover/DiscoverScreen.jsx')
const viewerScreen = read('src/components/live/ViewerLiveScreen.jsx')
const liveV2Css = read('src/styles/live/fam1-v2.css')
const chatCss = read('src/styles/live/fam1-chat.css')
const liveContract = read('src/styles/live/live-contract.css')
const giftTray = read('src/components/gifts/LiveGiftTray.jsx')
const giftSystem = read('src/hooks/useGiftSystem.js')
const liveActivity = read('src/hooks/useLiveActivity.js')
const giftEngine = read('src/features/gifts/renderer/gift-engine.js')
const giftAudio = read('src/features/gifts/renderer/gift-audio.js')
const giftEngineCss = read('src/styles/gifts/engine.css')

assert.match(app, /SPLASH_MINIMUM_MS = 1800/, 'Splash must remain visible long enough to avoid a one-frame flash.')
assert.match(index, /name="color-scheme" content="dark"/, 'Initial document must request a dark browser surface.')
assert.match(index, /html\s*\{[\s\S]*color-scheme:\s*dark/, 'HTML must paint dark before React loads.')
assert.match(manifest, /"background_color": "#07010d"/, 'PWA launch background must match the splash.')
assert.match(serviceWorker, /fameverse-beta-v22-device-truth/, 'Every device-truth release must rotate the installed PWA cache.')
assert.match(serviceWorker, /request\.mode === 'navigate'[\s\S]*fetchAndCache\(request, cache, '\/'\)[\s\S]*if \(fresh\) return fresh/, 'Installed PWA navigation must prefer fresh production HTML before cached fallback.')
assert.match(serviceWorker, /fv-shell-check/, 'The service worker must allow a network-only app-shell version check.')
assert.match(pwaUpdate, /shellAssetSignature/, 'Installed-device parity must compare the complete hashed app shell.')
assert.match(pwaUpdate, /currentShellSignature/, 'The running app must fingerprint the assets it is executing.')
assert.match(pwaUpdate, /latestShellSignature/, 'The running app must compare itself with the deployed asset shell.')
assert.match(pwaUpdate, /\.mobile-live-shell\.is-live, \.fv-viewer-live/, 'Updates must defer during host and viewer Live sessions.')

assert.match(liveChat, /className="fam-chat-stack fv-live-chat-feed"/, 'New Live chat must not reuse the legacy live-chat-overlay class.')
assert.match(liveChat, /className="fam-comment-composer fv-live-composer"/, 'New Live composer must not reuse the legacy live-comment-composer class.')
assert.match(liveChat, /className="fv-live-comment-entry"[\s\S]*className="fv-live-gift-button"[\s\S]*className="fv-live-send-button"/, 'Bottom order must remain chat, Gift, Send.')
assert.match(liveChat, /onClick=\{onGiftClick\}/, 'Gift button must have a real click handler.')
assert.match(liveChat, /onSubmit=\{submitComment\}/, 'Comment form must remain wired to submit.')
assert.match(chatCss, /grid-template-columns:\s*minmax\(0, 1fr\) 44px 44px/, 'Approved chat, Gift, Send layout must stay separate and compact.')
assert.match(chatCss, /\.fam-chat-line\s*\{[\s\S]*background:\s*transparent/, 'Normal comments must stay lightweight overlays.')

assert.match(liveHeader, /className="fam-live-creator-identity"/, 'Host identity must use the isolated no-box Live class.')
assert.doesNotMatch(liveHeader, /fam-creator-capsule/, 'Host identity must not reuse the legacy capsule class.')
assert.match(liveContract, /\.mobile-live-shell\.is-live \.fam-live-creator-identity[\s\S]*background:\s*transparent !important/, 'Final Live contract must enforce the unboxed host identity.')
assert.match(liveContract, /\.live-action-rail,[\s\S]*\.fam-action-rail[\s\S]*display:\s*none !important/, 'Final Live contract must block the removed vertical rail.')
assert.ok(main.trim().indexOf("./styles/live/live-contract.css") > main.trim().indexOf("./styles/base/pwa-update.css"), 'The active Live contract must load after every older stylesheet.')
assert.doesNotMatch(liveV2Css, /\.mobile-live-shell\.is-live\s+\.fam-creator-capsule/, 'Later pre-live styles must never repaint a box behind the creator identity.')
assert.match(liveHeader, />LIVE<\/span>/, 'Host header must show a clean LIVE badge, not developer sync text.')

assert.match(viewerScreen, /fv-viewer-live-name-row[\s\S]*fv-viewer-follow/, 'Follow must stay directly under the host identity.')
assert.match(viewerScreen, /onClick=\{toggleFollow\}/, 'Viewer Follow must stay functional.')
assert.match(viewerScreen, /onGiftClick=\{openGiftTray\}/, 'Viewer Gift must stay functional.')
assert.match(viewerScreen, /fv-viewer-live-f-menu[\s\S]*onClick=\{\(\) => setMenuOpen/, 'Viewer F menu must have a real toggle handler.')
assert.match(viewerScreen, /role="menuitem"[\s\S]*onClick=\{shareLive\}/, 'Viewer Share action must remain wired.')
assert.doesNotMatch(viewerScreen, /fv-viewer-live-actions/, 'Do not restore the vertical viewer action rail.')
assert.match(liveContract, /\.fv-viewer-live \.fam-comment-composer\.fv-live-composer[\s\S]*grid-template-columns:\s*minmax\(0, 1fr\) 44px 44px/, 'Viewer bottom row must use chat, Gift, Send before the F control.')

assert.match(liveScreen, /onGiftClick=\{\(\) => setGiftTrayOpen\(true\)\}/, 'Host Gift button must open the real gift tray.')
assert.match(liveActions, /className="fam-live-f-menu"/, 'Host extra controls must stay inside the F menu.')
assert.match(liveActions, /onClick=\{\(\) => setMenuOpen/, 'Host F menu toggle must remain functional.')
assert.match(liveActions, /runAction\(toggleMic\)/, 'Host mute control must remain wired.')
assert.match(liveActions, /runAction\(toggleCamera\)/, 'Host camera control must remain wired.')
assert.match(liveActions, /runAction\(flipCamera\)/, 'Host flip control must remain wired.')
assert.match(liveActions, /runAction\(shareRoom\)/, 'Host Share control must remain wired.')
assert.doesNotMatch(liveActions, /fam-action-rail/, 'Do not restore the old host vertical action rail.')

assert.match(preLive, /startGiftAudioSession\(\)[\s\S]*beginLive\(\)/, 'Go Live must start a persistent audio session inside the host user gesture.')
assert.match(discover, /startAudioSession\?\.\(\)[\s\S]*onOpenLiveRoom\?\.\(room\)/, 'Entering a viewer Live must unlock its persistent gift audio session inside the Watch gesture.')
assert.match(liveActivity, /remoteGiftRef\.current\?\.\(gift, quantity, payload\.sender\)/, 'Remote viewer gifts must enter the host/viewer gift playback path.')
assert.match(giftSystem, /stopAudioSession\?\.\(\)/, 'Leaving Live must close the persistent gift audio session.')
assert.match(giftSystem, /playPremiumGift[\s\S]*FameverseGiftEngine\?\.primeAudio\?\.\(\)/, 'Premium gift playback must re-arm audio before local or remote playback.')
assert.match(giftAudio, /createConstantSource/, 'Remote gift audio must keep an unlocked Web Audio session alive between user interactions.')
assert.match(giftAudio, /sessionActive/, 'Gift audio keep-alive must be scoped to an active host/viewer Live session.')
assert.match(giftEngine, /startAudioSession:\s*startGiftAudioSession/, 'Gift engine must expose persistent audio session start.')
assert.match(giftEngine, /stopAudioSession:\s*stopGiftAudioSession/, 'Gift engine must expose persistent audio session stop.')
assert.doesNotMatch(giftEngine, /playGiftChime\(\)/, 'Premium gifts must not add an unrequested synthetic intro chime.')
assert.doesNotMatch(giftAudio, /createOscillator|scheduleTone|playUnlockedChime/, 'Gift audio unlock must stay silent and never synthesize extra tones.')

assert.match(giftTray, /readyThumbnails/, 'Gift tray must track preview readiness.')
assert.match(giftTray, /live-gift-thumbnail-fallback/, 'Gift tray needs a branded fallback before video preview is ready.')
assert.match(giftTray, /onSeeked=/, 'Cinematic thumbnail must wait for the requested frame.')
assert.match(giftEngine, /\.mobile-live-shell\.is-live, \.fv-viewer-live/, 'Premium gifts must render for hosts and viewers.')
assert.match(giftEngineCss, /\.fv-gift-engine\.is-playing \.fv-gift-video\s*\{\s*opacity:\s*1/, 'Premium gift video must not reveal a black frame before playback starts.')
assert.match(giftEngineCss, /\.fv-gift-engine::before/, 'Premium gift loading state must stay branded instead of black.')

console.log('Live UX checks passed: device-truth delivery, isolated approved layout, working controls, persistent remote gift audio, and silent gift-video startup are locked.')
