import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

function read(path) {
  return readFileSync(new URL(`../${path}`, import.meta.url), 'utf8')
}

const app = read('src/App.jsx')
const index = read('index.html')
const manifest = read('public/manifest.webmanifest')
const serviceWorker = read('public/sw.js')
const liveScreen = read('src/components/live/LiveScreen.jsx')
const liveHeader = read('src/components/live/LiveHeader.jsx')
const liveActions = read('src/components/live/LiveActions.jsx')
const liveChat = read('src/components/live/LiveChat.jsx')
const preLive = read('src/components/live/PreLiveSetupPanel.jsx')
const viewerScreen = read('src/components/live/ViewerLiveScreen.jsx')
const viewerCss = read('src/styles/live/viewer-live.css')
const hostCss = read('src/styles/live/fam1-shell.css')
const chatCss = read('src/styles/live/fam1-chat.css')
const giftTray = read('src/components/gifts/LiveGiftTray.jsx')
const giftEngine = read('src/features/gifts/renderer/gift-engine.js')
const giftAudio = read('src/features/gifts/renderer/gift-audio.js')
const giftEngineCss = read('src/styles/gifts/engine.css')

assert.match(app, /SPLASH_MINIMUM_MS = 1800/, 'Splash must remain visible long enough to avoid a one-frame flash.')
assert.match(index, /name="color-scheme" content="dark"/, 'Initial document must request a dark browser surface.')
assert.match(index, /html\s*\{[\s\S]*color-scheme:\s*dark/, 'HTML must paint dark before React loads.')
assert.match(manifest, /"background_color": "#07010d"/, 'PWA launch background must match the splash.')
assert.match(serviceWorker, /APP_SHELL = \['\/'/, 'The root document must be pre-cached for instant PWA startup.')
assert.match(serviceWorker, /cache\.match\('\/'\)/, 'Navigation must have a cached root fallback.')

assert.match(liveChat, /className="live-comment-entry"[\s\S]*\{onGiftClick && \([\s\S]*className="live-comment-gift"[\s\S]*className="live-comment-send"/, 'Bottom order must remain chat, Gift, Send.')
assert.match(liveChat, /onClick=\{onGiftClick\}/, 'Gift button must have a real click handler.')
assert.match(liveChat, /onSubmit=\{submitComment\}/, 'Comment form must remain wired to submit.')
assert.match(chatCss, /grid-template-columns:\s*minmax\(0, 1fr\) 42px 42px/, 'Approved chat, Gift, Send layout must stay separate and compact.')
assert.match(chatCss, /\.fam-chat-line\s*\{[\s\S]*background:\s*transparent/, 'Normal comments must stay lightweight overlays.')

assert.match(viewerScreen, /fv-viewer-live-name-row[\s\S]*fv-viewer-follow/, 'Follow must stay directly under the host identity.')
assert.match(viewerScreen, /onClick=\{toggleFollow\}/, 'Viewer Follow must stay functional.')
assert.match(viewerScreen, /onGiftClick=\{openGiftTray\}/, 'Viewer Gift must stay functional.')
assert.match(viewerScreen, /fv-viewer-live-f-menu[\s\S]*onClick=\{\(\) => setMenuOpen/, 'Viewer F menu must have a real toggle handler.')
assert.match(viewerScreen, /role="menuitem"[\s\S]*onClick=\{shareLive\}/, 'Viewer Share action must remain wired.')
assert.doesNotMatch(viewerScreen, /fv-viewer-live-actions/, 'Do not restore the vertical viewer action rail.')
assert.match(viewerCss, /grid-template-columns:\s*minmax\(0, 1fr\) 42px 42px/, 'Viewer bottom row must match the approved chat, Gift, Send structure.')
assert.match(viewerCss, /\.fv-viewer-live-f-menu\s*\{[\s\S]*width:\s*54px/, 'Large glowing F control must remain at the far right.')

assert.match(liveScreen, /onGiftClick=\{\(\) => setGiftTrayOpen\(true\)\}/, 'Host Gift button must open the real gift tray.')
assert.match(liveActions, /className="fam-live-f-menu"/, 'Host extra controls must stay inside the F menu.')
assert.match(liveActions, /onClick=\{\(\) => setMenuOpen/, 'Host F menu toggle must remain functional.')
assert.match(liveActions, /runAction\(toggleMic\)/, 'Host mute control must remain wired.')
assert.match(liveActions, /runAction\(toggleCamera\)/, 'Host camera control must remain wired.')
assert.match(liveActions, /runAction\(flipCamera\)/, 'Host flip control must remain wired.')
assert.match(liveActions, /runAction\(shareRoom\)/, 'Host Share control must remain wired.')
assert.doesNotMatch(liveActions, /fam-action-rail/, 'Do not restore the old host vertical action rail.')
assert.doesNotMatch(hostCss, /\.fam-action-rail\s*\{/, 'Old host action rail CSS must remain removed.')
assert.match(liveHeader, />LIVE<\/span>/, 'Host header must show a clean LIVE badge, not developer sync text.')

assert.match(preLive, /primeGiftAudio\(\)[\s\S]*beginLive\(\)/, 'Go Live must explicitly unlock gift audio in the user gesture.')
assert.match(giftTray, /readyThumbnails/, 'Gift tray must track preview readiness.')
assert.match(giftTray, /live-gift-thumbnail-fallback/, 'Gift tray needs a branded fallback before video preview is ready.')
assert.match(giftTray, /onSeeked=/, 'Cinematic thumbnail must wait for the requested frame.')
assert.match(giftEngine, /\.mobile-live-shell\.is-live, \.fv-viewer-live/, 'Premium gifts must render for hosts and viewers.')
assert.match(giftEngine, /playGiftChime\(\)/, 'Premium gift playback must include audible Fameverse feedback.')
assert.match(giftAudio, /playUnlockPulse/, 'Gift audio must perform a mobile audio unlock pulse.')
assert.match(giftAudio, /gainValue/, 'Gift audio must retain explicit audible gain scheduling.')
assert.match(giftAudio, /pointerdown/, 'Gift audio must also be primed by normal user interaction.')
assert.match(giftEngineCss, /\.fv-gift-engine\.is-playing \.fv-gift-video\s*\{\s*opacity:\s*1/, 'Premium gift video must not reveal a black frame before playback starts.')
assert.match(giftEngineCss, /\.fv-gift-engine::before/, 'Premium gift loading state must stay branded instead of black.')

console.log('Live UX checks passed: approved layout, working control wiring, startup, gift preview, and host audio unlock are locked.')
