create table if not exists public.live_tap_totals (
  room_id uuid primary key references public.live_rooms(id) on delete cascade,
  raw_taps bigint not null default 0 check (raw_taps >= 0),
  eligible_taps bigint not null default 0 check (eligible_taps >= 0),
  updated_at timestamptz not null default now()
);

alter table public.live_tap_totals enable row level security;

drop policy if exists "authenticated users can read live tap totals" on public.live_tap_totals;
create policy "authenticated users can read live tap totals"
on public.live_tap_totals
for select
to authenticated
using (
  exists (
    select 1
    from public.live_rooms lr
    where lr.id = room_id
      and (lr.status = 'live' or lr.host_user_id = (select auth.uid()))
  )
);

create table if not exists public.live_tap_batches (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.live_rooms(id) on delete cascade,
  actor_user_id uuid not null references auth.users(id) on delete cascade,
  batch_id text not null check (char_length(batch_id) between 8 and 128),
  raw_tap_count integer not null default 0 check (raw_tap_count >= 0),
  eligible_tap_count integer not null default 0 check (eligible_tap_count >= 0),
  trust_score numeric(6,4) not null default 0 check (trust_score >= 0 and trust_score <= 1),
  classification text not null check (classification in ('trusted', 'reduced', 'rejected')),
  reasons text[] not null default '{}',
  taps_per_second numeric(10,2) not null default 0,
  interval_cv numeric(12,6),
  integrity_version text not null default 'FAM-TAP-2',
  created_at timestamptz not null default now(),
  unique (room_id, actor_user_id, batch_id)
);

alter table public.live_tap_batches enable row level security;

create or replace function public.record_live_tap_batch(
  p_room_id uuid,
  p_batch_id text,
  p_timestamps double precision[]
)
returns table (
  raw_tap_count integer,
  eligible_tap_count integer,
  trust_score numeric,
  classification text,
  reasons text[],
  taps_per_second numeric,
  interval_cv numeric,
  total_raw_taps bigint,
  total_eligible_taps bigint,
  integrity_version text
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_actor uuid := auth.uid();
  v_host uuid;
  v_status text;
  v_heartbeat timestamptz;
  v_raw integer := coalesce(array_length(p_timestamps, 1), 0);
  v_eligible integer := 0;
  v_trust numeric := 1;
  v_classification text := 'trusted';
  v_reasons text[] := '{}';
  v_tps numeric := 0;
  v_cv numeric := null;
  v_duration_ms double precision := 0;
  v_mean_interval double precision := null;
  v_stddev_interval double precision := null;
  v_inserted_id bigint;
  v_total_raw bigint := 0;
  v_total_eligible bigint := 0;
  v_index integer;
  v_delta double precision;
  v_deltas double precision[] := '{}';
  v_countable boolean := true;
begin
  if v_actor is null then
    raise exception 'not_authenticated' using errcode = '42501';
  end if;

  if p_batch_id is null or char_length(trim(p_batch_id)) < 8 or char_length(trim(p_batch_id)) > 128 then
    raise exception 'invalid_batch_id' using errcode = '22023';
  end if;

  select lr.host_user_id, lr.status, lr.heartbeat_at
    into v_host, v_status, v_heartbeat
  from public.live_rooms lr
  where lr.id = p_room_id;

  if not found then
    raise exception 'live_room_not_found' using errcode = 'P0002';
  end if;

  if exists (
    select 1
    from public.live_tap_batches b
    where b.room_id = p_room_id
      and b.actor_user_id = v_actor
      and b.batch_id = trim(p_batch_id)
  ) then
    select coalesce(t.raw_taps, 0), coalesce(t.eligible_taps, 0)
      into v_total_raw, v_total_eligible
    from public.live_tap_totals t
    where t.room_id = p_room_id;

    return query select
      0,
      0,
      0::numeric,
      'rejected'::text,
      array['replayed_batch']::text[],
      0::numeric,
      null::numeric,
      coalesce(v_total_raw, 0),
      coalesce(v_total_eligible, 0),
      'FAM-TAP-2'::text;
    return;
  end if;

  if v_status <> 'live' or v_heartbeat < now() - interval '45 seconds' then
    v_classification := 'rejected';
    v_trust := 0;
    v_reasons := array_append(v_reasons, 'inactive_live_session');
    v_countable := false;
  elsif v_actor = v_host then
    v_classification := 'rejected';
    v_trust := 0;
    v_reasons := array_append(v_reasons, 'host_self_tap');
    v_countable := false;
  elsif v_raw = 0 then
    v_classification := 'rejected';
    v_trust := 0;
    v_reasons := array_append(v_reasons, 'empty_batch');
    v_countable := false;
  elsif v_raw > 200 then
    v_classification := 'rejected';
    v_trust := 0;
    v_reasons := array_append(v_reasons, 'batch_too_large');
    v_countable := false;
  end if;

  if v_countable then
    for v_index in 1..v_raw loop
      if p_timestamps[v_index] is null or p_timestamps[v_index] < 0 then
        v_classification := 'rejected';
        v_trust := 0;
        v_reasons := array_append(v_reasons, 'invalid_timestamp');
        v_countable := false;
        exit;
      end if;

      if v_index > 1 then
        if p_timestamps[v_index] <= p_timestamps[v_index - 1] then
          v_classification := 'rejected';
          v_trust := 0;
          v_reasons := array_append(v_reasons, 'non_monotonic_timestamps');
          v_countable := false;
          exit;
        end if;
        v_delta := p_timestamps[v_index] - p_timestamps[v_index - 1];
        v_deltas := array_append(v_deltas, v_delta);
      end if;
    end loop;
  end if;

  if v_countable and v_raw > 1 then
    v_duration_ms := p_timestamps[v_raw] - p_timestamps[1];
    if v_duration_ms > 0 then
      v_tps := round((((v_raw - 1)::numeric / v_duration_ms::numeric) * 1000), 2);
    end if;

    select avg(x), stddev_pop(x)
      into v_mean_interval, v_stddev_interval
    from unnest(v_deltas) as x;

    if v_mean_interval is not null and v_mean_interval > 0 and v_stddev_interval is not null then
      v_cv := round((v_stddev_interval::numeric / v_mean_interval::numeric), 6);
    end if;

    if v_tps > 30 then
      v_classification := 'rejected';
      v_trust := 0;
      v_reasons := array_append(v_reasons, 'impossible_rate');
      v_countable := false;
    else
      if v_tps > 15 then
        v_trust := v_trust * 0.75;
        v_reasons := array_append(v_reasons, 'very_high_rate');
      end if;

      if v_raw >= 12 and v_cv is not null then
        if v_cv <= 0.015 then
          v_trust := v_trust * 0.50;
          v_reasons := array_append(v_reasons, 'near_perfect_timing');
        elsif v_cv <= 0.04 then
          v_trust := v_trust * 0.80;
          v_reasons := array_append(v_reasons, 'highly_repetitive_timing');
        end if;
      end if;

      v_trust := round(greatest(0, least(1, v_trust)), 4);
      if v_trust < 0.90 then
        v_classification := 'reduced';
      end if;
    end if;
  end if;

  if v_countable then
    v_eligible := round(v_raw * v_trust)::integer;
  else
    v_eligible := 0;
  end if;

  insert into public.live_tap_batches (
    room_id,
    actor_user_id,
    batch_id,
    raw_tap_count,
    eligible_tap_count,
    trust_score,
    classification,
    reasons,
    taps_per_second,
    interval_cv,
    integrity_version
  ) values (
    p_room_id,
    v_actor,
    trim(p_batch_id),
    case when v_countable then v_raw else 0 end,
    v_eligible,
    v_trust,
    v_classification,
    v_reasons,
    coalesce(v_tps, 0),
    v_cv,
    'FAM-TAP-2'
  )
  on conflict (room_id, actor_user_id, batch_id) do nothing
  returning id into v_inserted_id;

  if v_inserted_id is null then
    select coalesce(t.raw_taps, 0), coalesce(t.eligible_taps, 0)
      into v_total_raw, v_total_eligible
    from public.live_tap_totals t
    where t.room_id = p_room_id;

    return query select
      0,
      0,
      0::numeric,
      'rejected'::text,
      array['replayed_batch']::text[],
      0::numeric,
      null::numeric,
      coalesce(v_total_raw, 0),
      coalesce(v_total_eligible, 0),
      'FAM-TAP-2'::text;
    return;
  end if;

  if v_countable then
    insert into public.live_tap_totals (room_id, raw_taps, eligible_taps, updated_at)
    values (p_room_id, v_raw, v_eligible, now())
    on conflict (room_id) do update
      set raw_taps = public.live_tap_totals.raw_taps + excluded.raw_taps,
          eligible_taps = public.live_tap_totals.eligible_taps + excluded.eligible_taps,
          updated_at = now();
  end if;

  select coalesce(t.raw_taps, 0), coalesce(t.eligible_taps, 0)
    into v_total_raw, v_total_eligible
  from public.live_tap_totals t
  where t.room_id = p_room_id;

  return query select
    case when v_countable then v_raw else 0 end,
    v_eligible,
    v_trust,
    v_classification,
    v_reasons,
    coalesce(v_tps, 0),
    v_cv,
    coalesce(v_total_raw, 0),
    coalesce(v_total_eligible, 0),
    'FAM-TAP-2'::text;
end;
$$;

revoke all on function public.record_live_tap_batch(uuid, text, double precision[]) from public;
revoke all on function public.record_live_tap_batch(uuid, text, double precision[]) from anon;
grant execute on function public.record_live_tap_batch(uuid, text, double precision[]) to authenticated;
